version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./var/www:/var/www
    depends_on:
      - php

  php:
    image: php:latest
    volumes:
      - ./var/www:/var/www
